source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ZXBannerView_Example' do
  pod 'ZXBannerView', :path => '../'
  target 'ZXBannerView_Tests' do
    inherit! :search_paths
  end
end
